### PR TITLE
Edit delete module code

### LINKED ISSUE #113: Add/Change error message when wrong/missing parameters given for module commands
- Manual module add without all necessary parameters

### LINKED ISSUE #114: Change module modify/delete commands to use ModuleCode rather than Index

### LINKED ISSUE #145: Requesting for NUS Mods should timeout and error gracefully

### PR DESCRIPTION
**Pull request by waynewee**

### CODE REVIEW

File: src/main/java/igrad/commons/core/Messages.java [hunk 1]
```diff
@@ -11,6 +11,6 @@
     public static final String MESSAGE_COURSE_NOT_SET = "Sorry, you need to set a course first!";
     public static final String MESSAGE_SPECIFIER_NOT_SPECIFIED = "Please provide a non-empty specifier.\n%1$s";
 
-    public static final String MESSAGE_INVALID_MODULE_DISPLAYED_INDEX = "The module index provided is invalid";
+    public static final String MESSAGE_INVALID_MODULE_DISPLAYED_INDEX = "The module code provided is invalid";
```
Comment (nathanaelseen) [inline src/main/java/igrad/commons/core/Messages.java:14]: I think these messages should be placed (localised) in the respective Model classes instead of putting it here. The messages here are only those related to the whole (global) application

File: src/main/java/igrad/logic/parser/module/ModuleAddCommandParser.java [hunk 2]
```diff
@@ -57,18 +56,23 @@ public ModuleAddCommand parse(String args) throws ParseException {
...
+            : Optional.empty();
+        Optional<Semester> semester = argMultimap.getValue(PREFIX_SEMESTER).isPresent()
+            ? Optional.of(parseSemester(argMultimap.getValue(PREFIX_SEMESTER).get()))
+            : Optional.empty();
         Set<Tag> tagList = ParserUtil.parseTag(argMultimap.getAllValues(PREFIX_TAG));
 
-        Module module = new Module(title, moduleCode, credits, memo, semester, description, tagList);
+        Module module = new Module(title, moduleCode, credits);
+
+        memo.ifPresent(module::setMemo);
```
Comment (nathanaelseen) [inline src/main/java/igrad/logic/parser/module/ModuleAddCommandParser.java:73]: @waynewee i pulled  this PR to my com but it couldn't build because the `setMemo` method actually assigned a value to a final variable, `Memo`. Since this is urgent, I'll help you fix the code

File: src/main/java/igrad/logic/commands/ModuleEditCommand.java [hunk 3]
```diff
@@ -114,11 +91,19 @@ public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
         List<Module> lastShownList = model.getFilteredModuleList();
 
-        if (index.getZeroBased() >= lastShownList.size()) {
+        Optional<Module> moduleToEditOpt = Optional.empty();
```
Comment (nathanaelseen) [inline src/main/java/igrad/logic/commands/ModuleEditCommand.java:94]: @waynewee @yjskrs, I noticed that y'all probe the module/requirement list manually through using loops and streams, but I think there's no need to, as `UniqueRequirementList`/`UniqueModuleList` already provides a means to do so (`hasModule(..)` method). That being said, please do not call that method directly but instead use the `Model` public API interface methods `model.hasModule(..)`/`model.hasRequirement(...)` to (indirectly) call it

File: src/main/java/igrad/logic/parser/module/ModuleAddCommandParser.java (hunk 2 above)
Comment (nathanaelseen) [reply src/main/java/igrad/logic/parser/module/ModuleAddCommandParser.java:73]: Actually to be consistent with the existing code-base, we should not have setter-methods (mutators), and only getter (accessors)

**Review by nathanaelseen — APPROVED** [review]

File: src/main/java/igrad/logic/commands/ModuleEditCommand.java (hunk 3 above)
Comment (nathanaelseen) [reply src/main/java/igrad/logic/commands/ModuleEditCommand.java:94]: ok i take it back, actually i kinda like the design (of not having too many unnecessary/trivial methods in `Model` API)
